PhalSabzi/Models/Item.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhalSabzi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Carts = new HashSet<Cart>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Wishlists = new HashSet<Wishlist>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Pic_Path { get; set; }
        public string Pic_Title { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Season { get; set; }
        public string Category { get; set; }
        public string Enable_Flag { get; set; }
        public Nullable<int> Price { get; set; }
        public string Quantity { get; set; }
        public string Type { get; set; }
        public string Discription { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Sales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wishlist> Wishlists { get; set; }
    }
}

PhalSabzi/Areas/Admin/Controllers/ItemsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PhalSabzi.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhalSabzi.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ItemsController : Controller
    {
        PhalSabziEntities db = new PhalSabziEntities();
        // GET: Admin/Items
        public ActionResult Index()
        {
            if (TempData["Message"] != null)
                ViewBag.Message = TempData["Message"].ToString();
            var data = db.Items.Where(x => x.Enable_Flag == "Y").ToList();
            return View(data);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Item mod, HttpPostedFileBase file)
        {
            try
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = "";
                    var randomFile = "";
                    var uploadDir = "~/Items/Images";

                    System.IO.Directory.CreateDirectory(Server.MapPath(uploadDir));

                    fileName = file.FileName;
                    string extension = Path.GetExtension(file.FileName);
                    randomFile = DateTime.Now.ToString("yyyyMMddHHmmssfff") + "_" + Guid.NewGuid().ToString("N") +
                                 extension;

                    var filePath = Path.Combine(Server.MapPath(uploadDir), randomFile);
                    file.SaveAs(filePath);

                    mod.Pic_Path = randomFile;
                    //mod.Pic_Title = fileName;
                }
                mod.Created_Date = DateTime.Now;
                mod.CreatedBy = User.Identity.GetUserId();
                mod.Enable_Flag = "Y";
                db.Items.Add(mod);
                db.SaveChanges();
                TempData["Message"] = "Item Add Successfully!";
                return RedirectToAction("Index");
            }
            catch (DbEntityValidationException dbx)
            {
                string message =
                    dbx.EntityValidationErrors.SelectMany(validationErrors => validationErrors.ValidationErrors)
                        .Aggregate("",
                            (current, validationError) =>
                                current +
                                $"Property: {validationError.PropertyName} Error: {validationError.ErrorMessage}");

                ModelState.AddModelError("", message);
                TempData["Message"] = message;
                return RedirectToAction("Index");
            }
        }

        public ActionResult Edit(int? id)
        {
            var find = db.Items.Where(x => x.ID == id && x.Enable_Flag == "Y").FirstOrDefault();
            return View(find);
        }

        [HttpPost]
        public ActionResult Edit(Item mod, HttpPostedFileBase file, string Img)
        {
            try
            {
                if (file != null && file.ContentLength > 0)
                {
                    var fileName = "";
                    var randomFile = "";
                    var uploadDir = "~/Items/Images";

                    System.IO.Directory.CreateDirectory(Server.MapPath(uploadDir));

                    fileName = file.FileName;
                    string extension = Path.GetExtension(file.FileName);
                    randomFile = DateTime.Now.ToString("yyyyMMddHHmmssfff") + "_" + Guid.NewGuid().ToString("N") +
                                 extension;

                    var filePath = Path.Combine(Server.MapPath(uploadDir), randomFile);
                    file.SaveAs(filePath);

                    mod.Pic_Path = randomFile;
                    //mod.Pic_Title = fileName;
                }
                else
                {
                    mod.Pic_Path = Img;
                }
                mod.Updated_Date = DateTime.Now;
                mod.UpdatedBy = User.Identity.GetUserId();
                mod.Name = mod.Name;
                mod.Enable_Flag = "Y";
                db.Entry(mod).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TempData["Message"] = "Item Update Successfully!";
                return RedirectToAction("Index");
            }
            catch (DbEntityValidationException dbx)
            {
                string message =
                    dbx.EntityValidationErrors.SelectMany(validationErrors => validationErrors.ValidationErrors)
                        .Aggregate("",
                            (current, validationError) =>
                                current +
                                $"Property: {validationError.PropertyName} Error: {validationError.ErrorMessage}");

                ModelState.AddModelError("", message);
                TempData["Message"] = message;
                return RedirectToAction("Index");
            }
        }
       
        public ActionResult Delete(int? id)
        {
            var find = db.Items.Find(id);
            db.Items.Remove(find);
            //find.Enable_Flag = "D";
            db.SaveChanges();
            TempData["Message"] = "Item Delete Successfully!";
            return RedirectToAction("Index");
        }

        public ActionResult Dashboard()
        {
            return View();
        }

        public JsonResult DashboardCounters(int flag)
        {
            var Count = 0;

            switch (flag)
            {
                //count for Dashboard
                case 1:
                    Count = db.Items.Count();
                    break;
                case 2:
                    Count = db.AspNetUsers.Count();
                    break;
                case 3:
                    Count = db.Items.Count();
                    break;
                case 4:
                    Count = db.AspNetUsers.Count();
                    break;
                default:
                    Count = 0;
                    break;
            }
            return Json(new { count = Count });
        }

    }
}

PhalSabzi/Areas/Admin/Views/Items/Add.cshtml
@model PhalSabzi.Models.Item
@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section css{
}
<!-- //breadcrumb -->
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Add Item</h4>
            @using (Html.BeginForm("Add", "Items", new { area = "Admin" }, FormMethod.Post, new { id = "commentForm", @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
            {
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Name</label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder = "Name", required = "required", title = "Please Enter Item Name" })
                        @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Category</label>
                        @Html.DropDownListFor(x => x.Category,
    new List<SelectListItem> {
                          new SelectListItem { Value = "Fruits" , Text = "Fruits" },
                          new SelectListItem { Value = "Vegitables" , Text = "Vegitables" },
                               },
      "-Select-", new { @class = "js-example-basic-single", style = "width:100%" })
                        @Html.ValidationMessageFor(x => x.Category, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Season</label>
                        @Html.DropDownListFor(x => x.Season,
    new List<SelectListItem> {
                          new SelectListItem { Value = "Summer" , Text = "Summer" },
                          new SelectListItem { Value = "Winter" , Text = "Winter" },
                               },
      "-Select-", new { @class = "js-example-basic-single", style = "width:100%" })
                        @Html.ValidationMessageFor(x => x.Season, "", new { @class = "text-danger" })
                    </div>
                </div>
                    <div class="col-md-8">
            <div class="form-group">
                <label for="exampleInputName1">Price</label>
                @Html.TextBoxFor(x => x.Price, new { @class = "form-control", placeholder = "Price", required = "required", title = "Please Enter Item price" })
                @Html.ValidationMessageFor(x => x.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <label for="exampleInputName1">Quantity</label>
                @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control", placeholder = "Quantity", required = "required", title = "Please Enter Item quantity" })
                @Html.ValidationMessageFor(x => x.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <label for="exampleInputName1">Type</label>
                @Html.DropDownListFor(x => x.Type,
    new List<SelectListItem> {
                          new SelectListItem { Value = "Killo" , Text = "Killo" },
                          new SelectListItem { Value = "Dozen" , Text = "Dozen" },
                               },
      "-Select-", new { @class = "js-example-basic-single", style = "width:100%" })
                @Html.ValidationMessageFor(x => x.Type, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <label for="exampleInputName1">Sales/Permotions</label>
                @Html.TextBoxFor(x => x.Sales, new { @class = "form-control", placeholder = "Sales" })
                @Html.ValidationMessageFor(x => x.Sales, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <label for="exampleInputName1">Discription</label>
                @Html.TextAreaFor(x => x.Discription, new { @class = "form-control", placeholder = "Discription" })
                @Html.ValidationMessageFor(x => x.Discription, "", new { @class = "text-danger" })
            </div>
        </div>
                <div class="form-group">
                    <label>Picture upload</label>
                    <input type="file" name="file" id="imgInp" class="file-upload-default" required title="Please upload a Picture">
                    <div class="input-group col-md-8">
                        <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Picture">
                        <span class="input-group-append">
                            <button class="file-upload-browse btn btn-warning mdi mdi-upload" type="button"> Upload Picture &nbsp;&nbsp;</button>
                        </span>
                    </div>
                    <img id="blah" src="~/Team_Profiles/files/dummyUser_1.jpg" alt=Item_Image style="width:165px; height:165px;float:right;margin-top:-17%;margin-right:10%;" />
                </div>
                <button type="submit" class="btn btn-success mr-2">Submit</button>
                @Html.ActionLink("Back to List", "Index", "Items", new { area = "Admin" }, new { @class = "btn btn-success mr-2" })}
        </div>
    </div>
    </div>



    @section scripts{
        @*Start script for tags and file upload and validation*@
        <script src="~/Content/adminassets/node_modules/jquery-file-upload/js/jquery.uploadfile.min.js"></script>
        <script src="~/Content/adminassets/node_modules/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/Content/adminassets/js/file-upload.js"></script>
        <script src="~/Content/adminassets/js/form-validation.js"></script>
        @*End script for tags and file upload and validation*@

        <script>
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $('#blah').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]);
                }
            }
            $("#imgInp").change(function () {
                readURL(this);
            });
        </script>
    }

PhalSabzi/Areas/Admin/Views/Items/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section css{
    <link rel="stylesheet" href="~/Content/adminassets/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css" />
    <link rel="stylesheet" href="~/Content/adminassets/node_modules/jquery-toast-plugin/dist/jquery.toast.min.css">
    <link href="~/Content/assets/css/loaders.min.css" rel="stylesheet" />
<style>
    .line-scale div {
        background-color: #337ab7 !important;
        max-height: 26px;
    }

    a {
        color: black;
    }
</style>
}


<div class="row">
    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
        <div class="card card-statistics">
            <a href="~/Admin/Items/Index">
                <div class="card-body">
                    <div class="clearfix">
                        <div class="float-left">
                            <i class="mdi  mdi-file-powerpoint text-danger icon-lg"></i>
                        </div>
                        <div class="float-right">
                            <p class="card-text text-right">Total Items</p>
                            <div class="fluid-container">
                                <div id="L-3" class="line-scale"><div></div><div></div><div></div><div></div></div>
                                <h3 class="card-title font-weight-bold text-right mb-0" id="P-3" style="font-weight:700;"></h3>
                            </div>
                        </div>
                    </div>

                </div>
            </a>
        </div>
</div>
    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
        <div class="card card-statistics">
            <a href="~/Admin/Users/Index">
                <div class="card-body">
                    <div class="clearfix">
                        <div class="float-left">
                            <i class="mdi mdi-account-multiple-plus text-info icon-lg"></i>
                        </div>
                        <div class="float-right">
                            <p class="card-text text-right">Total Users</p>
                            <div class="fluid-container">
                                <div id="L-4" class="line-scale"><div></div><div></div><div></div><div></div></div>
                                <h3 class="card-title font-weight-bold text-right mb-0" id="P-4" style="font-weight:700;"></h3>
                            </div>
                        </div>
                    </div>

                </div>
            </a>
        </div>
    </div>
</div>


@section scripts{

    @Scripts.Render("~/bundles/indexbundle")
    <script src="~/Content/adminassets/js/dashboard.js"></script>
    <script>
        $(document).ready(function () {
            for (var i = 1; i < 4; i++) {
                load(i);
            }
        });

 function load(id) {

                $("#L-" + id).show();
                var getUrl = "/Items/DashboardCounters";
                $.ajax({
                    url: getUrl,
                    type: "POST",
                    data: { flag: id },
                    success: function (response) {
                        $("#P-" + id).html(response.count);
                        $("#L-" + id).hide();
                    },
                    complete: function (data) {
                    }
                });
            }
    </script>
}

PhalSabzi/Areas/Admin/Views/Items/Edit.cshtml
@model PhalSabzi.Models.Item
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section css{

}
<input type="hidden" id="notifyMessage" value="@ViewBag.Message" />

<!-- //breadcrumb -->
<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Edit Category</h4>
            @using (Html.BeginForm("Edit", "Items", new { area = "Admin" }, FormMethod.Post, new {  @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(x => x.ID)
                @Html.HiddenFor(x => x.Created_Date)
                @Html.HiddenFor(x => x.CreatedBy)
                @Html.HiddenFor(x => x.Enable_Flag)
                <input type="hidden" value="@Model.Pic_Path" name="Img" />

                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Name</label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder = "Name", required = "required", title = "Please Enter Item Name" })
                        @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Category</label>
                        @Html.DropDownListFor(x => x.Category,
    new List<SelectListItem> {
                          new SelectListItem { Value = "Fruits" , Text = "Fruits" },
                          new SelectListItem { Value = "Vegitables" , Text = "Vegitables" },
                               },
      "-Select-", new { @class = "js-example-basic-single", style = "width:100%" })
                        @Html.ValidationMessageFor(x => x.Category, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Season</label>
                        @Html.DropDownListFor(x => x.Season,
    new List<SelectListItem> {
                          new SelectListItem { Value = "Summer" , Text = "Summer" },
                          new SelectListItem { Value = "Winter" , Text = "Winter" },
                               },
      "-Select-", new { @class = "js-example-basic-single", style = "width:100%" })
                        @Html.ValidationMessageFor(x => x.Season, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Price</label>
                        @Html.TextBoxFor(x => x.Price, new { @class = "form-control", placeholder = "Price", required = "required", title = "Please Enter Item price" })
                        @Html.ValidationMessageFor(x => x.Price, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Quantity</label>
                        @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control", placeholder = "Quantity", required = "required", title = "Please Enter Item quantity" })
                        @Html.ValidationMessageFor(x => x.Quantity, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Type</label>
                        @Html.DropDownListFor(x => x.Season,
    new List<SelectListItem> {
                          new SelectListItem { Value = "Killo" , Text = "Killo" },
                          new SelectListItem { Value = "Dozen" , Text = "Dozen" },
                               },
      "-Select-", new { @class = "js-example-basic-single", style = "width:100%" })
                        @Html.ValidationMessageFor(x => x.Season, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Sales/Permotions</label>
                        @Html.TextBoxFor(x => x.Sales, new { @class = "form-control", placeholder = "Sales" })
                        @Html.ValidationMessageFor(x => x.Sales, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Discription</label>
                        @Html.TextAreaFor(x => x.Discription, new { @class = "form-control", placeholder = "Discription" })
                        @Html.ValidationMessageFor(x => x.Discription, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label>File upload</label>
                    <input type="file" name="file" id="imgInp" class="file-upload-default" title="Please Upload a Picture">
                    <div class="input-group col-md-8">
                        @Html.TextBoxFor(x => x.Pic_Path, new { @class = "form-control file-upload-info", placeholder = "Upload Image" })
                        @Html.ValidationMessageFor(x => x.Pic_Path, "", new { @class = "text-danger" })
                        <span class="input-group-append">
                            <button class="file-upload-browse btn btn-warning mdi mdi-upload" type="button"> Upload Picture &nbsp;&nbsp;</button>
                        </span>
                    </div>
                    @*<img id="blah" src="#" width="150" height="130" alt=Gallery_Image style="float:right;margin-top:-23%;" />*@
                    <a download href="~/Team_Profiles/Gallery/@(Model.Pic_Path ?? "dummy.jpg")">
                        <center>
                            @if (Model.Pic_Path == null)
                            {
                                <img id="blah" src="~/Items/Images/dummyUser_1.jpg" style="width:165px; height:165px;float:right;margin-top:-17%;margin-right:10%;" />

                            }
                            else
                            {
                                <img id="blah" src="~/Items/Images/@(Model.Pic_Path?? "dummy.jpg")" style="width: 165px; height: 165px;float:right;margin-top:-17%;margin-right:10%;" />
                            }
                        </center>
                    </a>
                </div>


                <button type="submit" class="btn btn-success mr-2">Submit</button>
                @Html.ActionLink("Back to List", "Index", "Items", new { area = "Admin" }, new { @class = "btn btn-success mr-2" })
            }
        </div>
    </div>
</div>



@section scripts{
    @*Start script for tags and file upload and validation*@
    <script src="~/Content/adminassets/node_modules/jquery-file-upload/js/jquery.uploadfile.min.js"></script>
    <script src="~/Content/adminassets/node_modules/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/Content/adminassets/js/file-upload.js"></script>
    <script src="~/Content/adminassets/js/form-validation.js"></script>
    @*End script for tags and file upload and validation*@

    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#blah').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        $("#imgInp").change(function () {
            readURL(this);
        });
    </script>
}

PhalSabzi/Areas/Admin/Views/Items/Index.cshtml
@model List<PhalSabzi.Models.Item>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section css{
    <link rel="stylesheet" href="~/Content/adminassets/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css" />
    <link rel="stylesheet" href="~/Content/adminassets/node_modules/jquery-toast-plugin/dist/jquery.toast.min.css">
}
<input type="hidden" id="notifyMessage" value="@ViewBag.Message" />
<div class="card">
    <div class="card-body">
        <div class="row">
            <a href="~/Admin/Items/Add"><button type="submit" class="btn btn-success btn-lg mr-2">Add New Item</button></a>

        </div>
    </div>
</div>
<br />

<div class="card">
    <div class="card-body">
        <h4 class="card-title">All Items</h4>
        <div class="row">
            <div class="col-12">
                <table id="order-listing" class="table table-hover" cellspacing="0">
                    <thead>
                        @{
                            int i = 1;
                        }

                        <tr>
                            <th>Sr #</th>
                            <th>Picture</th>
                            <th>Item Name</th>
                            <th>Category</th>
                            <th>Season</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td class="py-1">
                                    @if (item.Pic_Path != null)
                                    {
                                        <img src="~/Items/Images/@item.Pic_Path" alt="image" />
                                    }
                                    else
                                    {
                                        <img src="~/Content/adminassets/images/faces-clipart/pic-1.png" alt="image">
                                    }
                                    </td>
                                    <td>@item.Name</td>
                                    <td>@item.Category</td>
                                    <td>@item.Season</td>

                                    <td>
                                        @Html.ActionLink("Edit", "Edit", "Items", new { id = item.ID, area = "Admin" }, new { @class = "btn btn-outline-info" })
                                        @Html.ActionLink("Delete", "Delete", "Items", new { id = item.ID, area = "Admin" }, new { @class = "btn btn-outline-danger" })
                                    </td>
                                </tr>
                                i++;
                            }
                        }
                        else
                        {
                            <tr><td>No Data Available</td></tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/indexbundle")
}