PhalSabzi/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PhalSabzi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhalSabzi.Areas.Admin.Controllers
{
    public class UsersController : Controller
    {
        PhalSabziEntities db = new PhalSabziEntities();
        // GET: Admin/Users
        public ActionResult Index()
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var data = userManager.Users.ToList();
            return View(data);
        }

        public ActionResult Detail(string id)
        {
            var detail = db.AspNetUsers.Where(x => x.Id == id).FirstOrDefault();
            return View(detail);
        }

        public ActionResult AssignRole(string userName, string roleName)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));

            if (userName != null && roleName != null)
            {
                if (!roleManager.RoleExists("Admin"))
                {
                    roleManager.Create(new IdentityRole("Admin"));
                }

                if (userManager.Users.Any(x => x.UserName == userName))
                {
                    var user = userManager.FindByName(userName);
                    // Add User To Role
                    if (userManager.IsInRole(user.Id, "Admin"))
                    {
                        userManager.RemoveFromRoles(user.Id, "Admin");
                        TempData["Message"] = "Admin Rights Removed!";
                    }
                }
            }
            else
            {
                if (!roleManager.RoleExists("Admin"))
                {
                    roleManager.Create(new IdentityRole("Admin"));
                }
                if (userManager.Users.Any(x => x.UserName == userName))
                {
                    var user = userManager.FindByName(userName);
                    // Add User To Role
                    if (!userManager.IsInRole(user.Id, "Admin"))
                    {
                        userManager.AddToRole(user.Id, "Admin");
                        TempData["Message"] = "Admin Rights Added!";
                    }
                }
            }
            db.SaveChanges();
            return RedirectToAction("Dashboard");
        }


        public ActionResult UserShope(string id,string view)
        {
            //var userid = User.Identity.GetUserId();
            if (view=="shopping")
            {
                var usershop = db.Carts.Where(x => x.User_ID == id && x.Enable_Flag == "Confirmed").ToList();
                return PartialView("~/Areas/Admin/Views/Users/_UserShopePartial.cshtml", usershop);
            }
            else
            {
                var wishlist = db.Wishlists.Where(x => x.User_ID == id).ToList();
                return PartialView("~/Areas/Admin/Views/Users/_WishlistPartial.cshtml", wishlist);

            }
        }
    }
}

PhalSabzi/Areas/Admin/Views/Users/Detail.cshtml
@*@model PhalSabzi.Models.AspNetUser*@
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Detail";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section css{
    <link rel="stylesheet" href="~/Content/adminassets/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css" />
    <link rel="stylesheet" href="~/Content/adminassets/node_modules/jquery-toast-plugin/dist/jquery.toast.min.css">
}

<input type="hidden" value="@Model.Id" id="userid" />
<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-4">User Detail</h5>
                <div class="table-responsive">
                <table id="order-listing" class="table table-hover" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>CNIC</th>
                                <th>Address</th>
                            </tr>
                        </thead>
                        <tbody>

                            <tr>
                                <td>@Model.UserName</td>
                                <td>@Model.Email</td>
                                <td>@Model.PhoneNumber</td>
                                <td>@Model.CNIC</td>
                                <td>@Model.Address</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <br />
                @Html.ActionLink("Back to List", "Index", "Users", new { area = "Admin" }, new { @class = "btn btn-success mr-2" })
            </div>
        </div>
    </div>
</div>
<button type="button" id="shoptbtn" value="shopping" class="btn btn-success mr-2">User Shopping Details</button>&nbsp; &nbsp; &nbsp;
<button type="button" id="wishlisttbtn" value="wishlist" class="btn btn-success mr-2">User WishList Details</button>

<br />
<br />

<div id="shopepartial">
</div>

<div id="wishlistpartial">
</div>


@section scripts{
@Scripts.Render("~/bundles/indexbundle")

    <script>

        $("#shoptbtn").on('click', function () {
            debugger;
            var userid = $("#userid").val();
            var btnval = $("#shoptbtn").val();
            var getUrl = "/Users/UserShope";
            //ajax request
            $.ajax({
                url: getUrl,
                type: "GET",
                data: { id: userid, view: btnval },
                success: function (result) {
                    $('#shopepartial').html(result);
                    $('#wishlistpartial').hide();
                    $('#shopepartial').show();
                },
                error: function (res) {
                    //error
                }
            });
        });

        $("#wishlisttbtn").on('click', function () {
            debugger;
            var userid = $("#userid").val();
            var btnval = $("#wishlisttbtn").val();
            var getUrl = "/Users/UserShope";
            //ajax request
            $.ajax({
                url: getUrl,
                type: "GET",
                data: { id: userid, view: btnval },
                success: function (result) {
                    $('#wishlistpartial').html(result);
                    $('#shopepartial').hide();
                    $('#wishlistpartial').show();
                },
                error: function (res) {
                    //error
                }
            });
        });

    </script>

}

PhalSabzi/Areas/Admin/Views/Users/Index.cshtml
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section css{
    <link rel="stylesheet" href="~/Content/adminassets/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css" />
    <link rel="stylesheet" href="~/Content/adminassets/node_modules/jquery-toast-plugin/dist/jquery.toast.min.css">

<style>
    .status-flag {
        width: 81px;
    }

    .admin-btn {
        width: 139.92px;
    }
</style>

}
<input type="hidden" id="notifyMessage" value="@ViewBag.Message" />
@*<div class="card">
    <div class="card-body">
        <div class="row">
            <a href="~/Admin/Items/Add"><button type="submit" class="btn btn-success btn-lg mr-2">Add New Item</button></a>

        </div>
    </div>
</div>
<br />*@

<div class="card">
    <div class="card-body">
        <h4 class="card-title">All Users</h4>
        <div class="row">
            <div class="col-12">
                <table id="order-listing" class="table table-hover" cellspacing="0">
                    <thead>
                        @{
                            int i = 1;
                        }

                        <tr>
                            <th>Sr #</th>
                            <th>Image</th>
                            <th>User Name</th>
                            @*<th>Email</th>*@
                            <th>Action</th>

                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td class="py-1">
                                            <img src="~/Content/adminassets/images/faces-clipart/pic-1.png" alt="image">
                                    </td>
                                    <td>@item.UserName</td>
                                    @*<td>@item.Email</td>*@
                                    @if (item.Roles.Count == 1)
                                    {
                                        <td><label class="badge badge-success status-flag">Admin</label></td>
                                        <td>
                                            @Html.ActionLink("Remove Admin", "AssignRole", "Users", new { userName = item.UserName, roleName = "Admin", area = "Admin" }, new { @class = "btn btn-outline-danger " })
                                        </td>
                                    }
                                    else
                                    {
                                        <td><label class="badge badge-danger status-flag">User</label></td>
                                        <td>
                                            @Html.ActionLink("Made Admin", "AssignRole", "Users", new { userName = item.UserName, area = "Admin" }, new { @class = "btn btn-outline-success admin-btn" })
                                        </td>
                                    }
                                    <td>
                                        @Html.ActionLink("Disable", "Disable", "Users", new { id = item.Id, area = "Admin" }, new { @class = "btn btn-outline-danger" })
                                    </td>
                                    <td>
                                        @Html.ActionLink("Detail", "Detail", "Users", new { id = item.Id, area = "Admin" }, new { @class = "btn btn-outline-success " })
                                    </td>

                                </tr>
                                i++;
                            }
                        }
                        else
                        {
                            <tr><td>No Data Available</td></tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


@section scripts{
    @Scripts.Render("~/bundles/indexbundle")
}

PhalSabzi/Areas/Admin/Views/Users/_UserShopePartial.cshtml
<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-4">User Shopping Details</h5>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Sr#</th>
                                <th class="border-bottom-0">Item Name</th>
                                <th class="border-bottom-0">Season</th>
                                <th class="border-bottom-0">Category</th>
                                <th class="border-bottom-0">Type</th>
                                <th class="border-bottom-0">Quantity</th>
                                <th class="border-bottom-0">Price/KG</th>
                                <th class="border-bottom-0">Total Price</th>
                                <th class="border-bottom-0">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{

                                int i = 1;
                                foreach (var item in Model)
                                {
                                        DateTime dt = item.Creation_Date;
                                        string date = dt.ToString("dd-MM-yyyy");
                                    <tr>
                                        <td>@i</td>
                                        <td>@item.Item.Name</td>
                                        <td>@item.Item.Season</td>
                                        <td>@item.Item.Category</td>
                                        <td>@item.Item.Type</td>
                                        <td>@item.Quantity</td>
                                        <td>@item.Item.Price</td>
                                        <td>@item.Total</td>
                                        <td>@date</td>
                                    </tr>
                                    i++;
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <br />
            </div>
        </div>
    </div>
</div>

PhalSabzi/Areas/Admin/Views/Users/_WishlistPartial.cshtml
<div class="row">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-4">User Wishlist Details</h5>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="border-bottom-0">Item Name</th>
                                <th class="border-bottom-0">Price/KG</th>
                                <th class="border-bottom-0">Season</th>
                                <th class="border-bottom-0">Category</th>
                                <th class="border-bottom-0">Type</th>
                                <th class="border-bottom-0">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                if (Model.Count > 0)
                                {
                                    int i = 1;
                                    foreach (var item in Model)
                                    {
                                        DateTime dt = item.Creation_Date;
                                        string date = dt.ToString("dd-MM-yyyy");
                                        <tr>
                                            <td>@item.Item.Name</td>
                                            <td>@item.Item.Price</td>
                                            <td>@item.Item.Season</td>
                                            <td>@item.Item.Category</td>
                                            <td>@item.Item.Type</td>
                                            <td>@date</td>
                                        </tr>
                                        i++;
                                    }
                                }
                                else
                                {
                                   <td>
                                        There is no item in wishlist yet!
                                   </td>
                                }

                            }

                        </tbody>
                    </table>
                </div>
                <br />
            </div>
        </div>
    </div>
</div>