PhalSabzi/Areas/Admin/Controllers/RoleAssignController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PhalSabzi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace PhalSabzi.Areas.Admin.Controllers
{
    public class RoleAssignController : Controller
    {
        PhalSabziEntities db = new PhalSabziEntities();
        // GET: Admin/RoleAssign
        public ActionResult Index()
        {
            Assembly asm = Assembly.GetExecutingAssembly();
            ViewBag.contrler = asm.GetTypes().Where(type => typeof(Controller).IsAssignableFrom(type)).Select(x => x.Name);

            var list = db.AspNetRoles.ToList();
            return View(list);
        }

        public ActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateRole(string roleName)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));

            if (roleName != null)
            {
                if (!roleManager.RoleExists(roleName))
                {
                    roleManager.Create(new IdentityRole(roleName));
                }
                TempData["Message"] = "Role Created!";

                //if (userManager.Users.Any(x => x.UserName == userName))
                //{
                //    var user = userManager.FindByName(userName);
                //    // Add User To Role
                //    if (userManager.IsInRole(user.Id, "Admin"))
                //    {
                //        userManager.RemoveFromRoles(user.Id, "Admin");
                //        TempData["Message"] = "Admin Rights Removed!";
                //    }
                //}
            }
            else
            {
                TempData["Message"] = "Role Already Exist!";

                //if (!roleManager.RoleExists("Admin"))
                //{
                //    roleManager.Create(new IdentityRole("Admin"));
                //}
                //if (userManager.Users.Any(x => x.UserName == userName))
                //{
                //    var user = userManager.FindByName(userName);
                //    // Add User To Role
                //    if (!userManager.IsInRole(user.Id, "Admin"))
                //    {
                //        userManager.AddToRole(user.Id, "Admin");
                //        TempData["Message"] = "Admin Rights Added!";
                //    }
                //}
            }
            return View();
        }

        [HttpPost]
        public JsonResult GetValues(myclass[] res)
        {
            return Json(new { res=true },JsonRequestBehavior.AllowGet);
        }

        public class myclass
        {
            public string rolename { get; set; }
            public string contname { get; set; }
        }
    }
}

PhalSabzi/Areas/Admin/Views/RoleAssign/CreateRole.cshtml
@{
    ViewBag.Title = "CreateRole";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Add Role</h4>
            @using (Html.BeginForm("CreateRole", "RoleAssign", new { area = "Admin" }, FormMethod.Post, new { id = "commentForm", @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
            {
                <div class="col-md-8">
                    <div class="form-group">
                        <label for="exampleInputName1">Name</label>
                        <input type="text" name="roleName" class="form-control"/>
                        @*@Html.TextBox("roleName", new { @class = "form-control", placeholder = "Name"})*@
                        @*@Html.ValidationMessage("roleName", "", new { @class = "text-danger" })*@
                    </div>
                </div>
                <button type="submit" class="btn btn-success mr-2">Submit</button>
                @Html.ActionLink("Back to List", "Index", "Items", new { area = "Admin" }, new { @class = "btn btn-success mr-2" })}
        </div>
    </div>
</div>

PhalSabzi/Areas/Admin/Views/RoleAssign/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@section css{
    <link rel="stylesheet" href="~/Content/adminassets/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css" />
    <link rel="stylesheet" href="~/Content/adminassets/node_modules/jquery-toast-plugin/dist/jquery.toast.min.css">
}

<input type="hidden" id="notifyMessage" value="@ViewBag.Message" />
<div class="card">
    <div class="card-body">
        <div class="row">
            <a href="~/Admin/Items/Add"><button type="submit" class="btn btn-success btn-lg mr-2">Add New Item</button></a>
            <a href="~/Admin/RoleAssign/CreateRole"><button type="submit" class="btn btn-success btn-lg mr-2">Add New Role</button></a>
        </div>
    </div>
</div>
<br />


<div class="card">
    <div class="card-body">
        <h4 class="card-title">All Roles</h4>
        <div class="row">
            <div class="col-12">
                <table id="order-listing" class="table table-hover " cellspacing="0">
                    <thead>
                        @*@{
                                int i = 1;
                            }*@

                        <tr>
                            <th>Role Name</th>
                            <th>Controller Name</th>

                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {

                            <tr>

                                <td>
                                    @foreach (var item in Model)
                                    {
                                        <input type="checkbox" name="rolename" class="myval" value="@item.Name" />@item.Name
                                    }
                                </td>
                                <td>
                                    @foreach (var item in ViewBag.contrler)
                                    {
                                        <input type="checkbox" name="contname" class="mycont" value="@item" />@item
                                    }
                                </td>
                                <td>
                                    @Html.ActionLink("Add", "GetValues", "RoleAssign", new { }, new { @class = "btn btn-outline-info click" })
                                    @*@Html.ActionLink("Delete", "Delete", "Items", new { }, new { @class = "btn btn-outline-danger" })*@
                                </td>
                            </tr>

                        }
                        else
                        {
                            <tr><td>No Data Available</td></tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/indexbundle")

    <script>
        $('input[type="checkbox"]').click(function () {
            checkAll();
        });
        function checkAll() {
           
            $('input[type="checkbox"]:checked').each(function () {
                var objArr = [];
                debugger;
                var itemVal = {};
                ///alert('selected: ' + $(this).val());
                itemVal[$(this).attr('name')] = $(this).val();
                objArr.push(itemVal);

            });
            Save(objArr)
        }
        //$(".click").click(function () {
        //    var objArr = [];
        //    $('#order-listing tr:has(td)').find('input[type="checkbox"]').each(function () {
        //        debugger;
        //        if ($(this).prop("checked") == true) {
        //            //var isChecked = $(this).prop("checked");
        //            var itemVal = {};
        //            debugger;
        //            //if (e > 0) {
        //            //$(this).find(".multTotal").each(function () {
        //            //    itemVal[$(this).attr('name')] = $(this).find('span').text();
        //            //});
        //            $.each($("input[name='case[]']:checked"), function () {
        //                itemVal[$(this).attr('name')] = $(this).val();
        //            });
        //            $(this).find(".mycont").each(function () {
        //                itemVal[$(this).attr('name')] = $(this).val();
        //            });
        //            objArr.push(itemVal);
        //            //}
        //        }
        //    });
        //    Save(objArr)
        //});

        function Save(objArr) {
            debugger;
            var getUrl = "/Admin/RoleAssign/GetValues";
            //debugger;
            $.ajax({
                type: "POST",
                url: getUrl,
                data: { res: objArr },
                success: function (res) {
                    if (res.res == true) {
                    }
                    //data - response from server
                },
                error: function (textStatus, errorThrown) {
                }
            });
        }

    </script>
}